### PR TITLE
Added darkmode

### PR DESCRIPTION
**Pull request by LuggaPugga**
As seen in the screenshots i added darkmode to geonotes.
I kept the original look and feel of the website but added a dark theme.

* Landing page
Screenshot from 2024-04-28 17-47-34
* About page
Screenshot from 2024-04-28 17-41-10
* Add GeoNote form
Screenshot from 2024-04-28 17-41-26
* Footer
Screenshot from 2024-04-28 17-40-21
* Login
Screenshot from 2024-04-28 17-47-50
* Account page
image

### CODE REVIEW

**Comment by LuggaPugga** [comment]
any updates?

**Comment by NonSwag** [comment]
any chance this is going to be merged
the page looks way better like this

**Comment by andrewheekin** [comment]
@LuggaPugga thanks for this dark mode feature! 

One small ask - can you update the PR to lint the code to use tab = 2 spaces and keep all other non-css changes the same (ex, on GeoNoteSearch, Navbar, etc)?

Let me know if you'd like me to add an editorconfig file to make this easier

**Comment by LuggaPugga** [comment]
> @LuggaPugga thanks for this dark mode feature!
> 
> One small ask - can you update the PR to lint the code to use tab = 2 spaces and keep all other non-css changes the same (ex, on GeoNoteSearch, Navbar, etc)?
> 
> Let me know if you'd like me to add an editorconfig file to make this easier

I changed back the indentations but I don't know what you mean with other changes, could you be more precise?

**Review by andrewheekin — APPROVED** [review]

**Pull request merged**
